
[api]
schemas = ["private", "public",  "pgmq_public"]

[db]
major_version="15"

[functions.receive-email]
enabled = true
verify_jwt = false
import_map = "./functions/receive-email/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/receive-email/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/receive-email/*.html" ]

[functions.worker]
enabled = true
verify_jwt = true
import_map = "./functions/worker/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/worker/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/worker/*.html" ]

[storage.buckets."gh-vehicle-photos"]
public = false
file_size_limit = "50MiB"
objects_path = "./seed_img"
