import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/lib/theme-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "GH Lead Generator Dashboard",
  description: "View company and contact data generated by Izzy's automated pipeline.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <ThemeProvider>
          <main className="flex-1 flex flex-col">
            {children}
          </main>
          <footer className="border-t bg-background px-4 py-6 text-center text-sm text-muted-foreground">
            Created by Izzy Lerman. <a href="mailto:izzylerman14@gmail.com" className="underline hover:text-foreground">izzylerman14@gmail.com</a>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
