CREATE TABLE public."vehicle-photos" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE, -- file name from storage
  status TEXT DEFAULT 'unprocessed', 
  created_at TIMESTAMPTZ DEFAULT NOW(),
  company_id INTEGER DEFAULT NULL,
  CONSTRAINT fk_company
    FOREIGN KEY (company_id) REFERENCES "vehicle-photos"(id)
    ON DELETE SET NULL

);

ALTER TABLE public."vehicle-photos" ENABLE ROW LEVEL SECURITY;

create policy "block_all"
on "public"."vehicle-photos"
for ALL
to public
using (false)
with check (false);
