name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dashboard

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: dashboard/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Run TypeScript type check
      run: npx tsc --noEmit

    - name: Run linter
      run: npm run lint

    - name: Build application
      run: npm run build

  backend-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Setup Supabase CLI
      uses: supabase/setup-cli@v1
      with:
        version: latest

    - name: Start Supabase local development setup
      run: supabase start

    - name: Run database migrations
      run: supabase db reset --local

    - name: Run Deno function tests
      env:
        SUPABASE_URL: http://127.0.0.1:54321
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY_LOCAL }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        VISION_API_KEY: ${{ secrets.VISION_API_KEY }}
        ANTHROPIC_API_URL: https://api.anthropic.com
        VISION_API_URL: https://vision.googleapis.com
        WORKER_URL: http://127.0.0.1:54321/functions/v1/worker
      run: deno test --allow-all --env-file=./supabase/functions/.env ./supabase

    - name: Run database tests
      run: supabase test db

  e2e-tests:
    runs-on: ubuntu-latest
    needs: [frontend-tests, backend-tests]

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: dashboard/package-lock.json

    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Setup Supabase CLI
      uses: supabase/setup-cli@v1
      with:
        version: latest

    - name: Start Supabase local development setup
      run: supabase start

    - name: Run database migrations
      run: supabase db reset --local

    - name: Deploy functions locally
      run: supabase functions serve --no-verify-jwt &

    - name: Wait for functions to be ready
      run: sleep 10

    - name: Install dashboard dependencies
      working-directory: ./dashboard
      run: npm ci

    - name: Build dashboard
      working-directory: ./dashboard
      run: npm run build

    - name: Start dashboard
      working-directory: ./dashboard
      run: npm run start &

    - name: Wait for dashboard to be ready
      run: sleep 10

    - name: Run E2E tests
      env:
        SUPABASE_URL: http://127.0.0.1:54321
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY_LOCAL }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        VISION_API_KEY: dummy-key-not-used-with-mocks
        ANTHROPIC_API_URL: https://api.anthropic.com
        VISION_API_URL: https://vision.googleapis.com
        WORKER_URL: http://127.0.0.1:54321/functions/v1/worker
        RECEIVE_EMAIL_URL: http://127.0.0.1:54321/functions/v1/receive-email
        DASHBOARD_URL: http://localhost:3000
        USE_MOCK_VISION: 'true'
        E2E_REAL_APIS: 'true'
      run: deno test --allow-all ./tests/e2e/

    - name: Upload test artifacts
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-artifacts
        path: |
          tests/e2e/screenshots/
          tests/e2e/logs/